default:
  stackName: cce
  stackNameNoDash: Cce
  params:
    - name: DockerPassword
      value: '{{DOCKER_PASSWORD}}'
    - name: DockerEmail
      value: '{{DOCKER_EMAIL}}'
    - name: CmrPassword
      value: '{{CMR_PASSWORD}}'

  communityConfiguration:
    ApiTokenDefault:
      handler: index.googleToken

  apiStage: dev

  vpc:
    vpcId: vpc-e61ddf9e
    subnets:
      - subnet-ef13ced0

  ecs:
    instanceType: t2.xlarge
    desiredInstances: 3
    maxInstances: 3
    availabilityZone: us-east-1e
    amiid: ami-aff65ad2
    publicIp: true
    restartTasksOnDeploy: true
    keyPairName: abarciauskas-ecs-2
    docker:
      username: cumuluss
    services:
      DownloadTiles:
        image: cumuluss/cumulus-ecs-task-python:0.0.1
        cpu: 400
        memory: 700
        count: 3
        envs:
          AWS_DEFAULT_REGION:
            function: Fn::Sub
            value: '${AWS::Region}'
        commands:
          - function: Ref
            value: DownloadTilesActivity
          - function: Ref
            value: ViirsProcessingLambdaFunction

  activities:
    - name: DownloadTiles

  buckets:
    internal: cumulus-devseed-internal
    private: cumulus-devseed-private
    protected: cumulus-devseed-protected

  iams:
    instanceProfile: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:instance-profile/cce-ecs'
    ecsRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/cce-ecs'
    lambdaApiGatewayRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/cce-lambda-api-gateway'
    lambdaProcessingRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/cce-lambda-processing'
    stepRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/cce-steprole'

  urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

    # if not specified the value of the apigateway backend endpoint is used
    # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

    # if not specified the value of the apigateway dist url is used
    # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
  users:
    - username: barciaai@gmail.com
    - username: alireza@developmentseed.org
