default:
  stackName: sez
  stackNameNoDash: sez
  params:
    - name: DockerPassword
      value: '{{DOCKER_PASSWORD}}'
    - name: DockerEmail
      value: '{{DOCKER_EMAIL}}'
    - name: CmrPassword
      value: '{{CMR_PASSWORD}}'

  communityConfiguration:
    ApiTokenDefault:
      handler: index.googleToken

  apiStage: dev

  vpc:
    vpcId: vpc-dfe524ba
    subnets:
      - subnet-ced1f5e6

  ecs:
    instanceType: t2.xlarge
    desiredInstances: 1
    maxInstances: 1
    availabilityZone: us-east-1c
    amiid: ami-a7a242da
    publicIp: true
    restartTasksOnDeploy: true
    volumeSize: 150
    docker:
      username: cumulususer
    services:
      DownloadTiles:
        image: cumuluss/cumulus-geolambda:0.0.4
        cpu: 400
        memory: 700
        count: 1
        envs:
          AWS_DEFAULT_REGION:
            function: Fn::Sub
            value: '${AWS::Region}'
        commands:
          - cumulus-ecs-task
          - '--activityArn'
          - function: Ref
            value: DownloadTilesActivity
          - '--lambdaArn'
          - function: Ref
            value: ViirsProcessingLambdaFunction

  activities:
    - name: DownloadTiles
  
  system_bucket: '{{buckets.internal.name}}'

  buckets:
    internal:
      name: cumulus-developmentseed-internal
      type: internal
    private:
      name: cumulus-developmentseed-private
      type: private
    protected:
      name: cumulus-developmentseed-protected
      type: protected

  iams:
    instanceProfile: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:instance-profile/sez-ecs'
    ecsRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/sez-ecs'
    lambdaApiGatewayRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/sez-lambda-api-gateway'
    lambdaProcessingRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/sez-lambda-processing'
    stepRoleArn: 'arn:aws:iam::{{AWS_ACCOUNT_ID}}:role/sez-steprole'

  urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

    # if not specified the value of the apigateway backend endpoint is used
    # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

    # if not specified the value of the apigateway dist url is used
    # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
