default:
  stackName: cce
  stackNameNoDash: Cce
  params:
    - name: DockerPassword
      value: '{{DOCKER_PASSWORD}}'
    - name: DockerEmail
      value: '{{DOCKER_EMAIL}}'
    - name: CmrPassword
      value: '{{CMR_PASSWORD}}'

  communityConfiguration:
    ApiTokenDefault:
      handler: index.googleToken

  apiStage: dev

  vpc:
    vpcId: vpc-e61ddf9e
    subnets:
      - subnet-ef13ced0

  ecs:
    instanceType: t2.small
    desiredInstances: 1
    availabilityZone: us-east-1e
    amiid: ami-a7a242da
    publicIp: true
    restartTasksOnDeploy: true
    docker:
      username: aimeeb2
    services:
      HelloWorld:
        image: aimeeb2/cumulus-ecs-task-python:0.0.1
        cpu: 400
        memory: 700
        count: 1
        envs:
          AWS_DEFAULT_REGION:
            function: Fn::Sub
            value: '${AWS::Region}'
        commands:
          - function: Ref
            value: HelloWorldActivity

  activities:
    - name: HelloWorld

  buckets:
    internal: cumulus-devseed-internal
    private: cumulus-devseed-private
    protected: cumulus-devseed-protected

  iams:
    instanceProfile: 'arn:aws:iam::433612427488:instance-profile/cce-ecs'
    ecsRoleArn: 'arn:aws:iam::433612427488:role/cce-ecs'
    lambdaApiGatewayRoleArn: 'arn:aws:iam::433612427488:role/cce-lambda-api-gateway'
    lambdaProcessingRoleArn: 'arn:aws:iam::433612427488:role/cce-lambda-processing'
    stepRoleArn: 'arn:aws:iam::433612427488:role/cce-steprole'

  urs_url: https://uat.urs.earthdata.nasa.gov/ #make sure to include the trailing slash

    # if not specified the value of the apigateway backend endpoint is used
    # api_backend_url: https://apigateway-url-to-api-backend/ #make sure to include the trailing slash

    # if not specified the value of the apigateway dist url is used
    # api_distribution_url: https://apigateway-url-to-distribution-app/ #make sure to include the trailing slash

  # URS users who should have access to the dashboard application.
  users:
    - username: barciaai@gmail.com
    - username: alireza@developmentseed.org
