default:
  prefix: aimee-deploy
  stackName: aimee-deploy-iam
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM
  buckets:
    internal: cumulus-devseed-internal
    private: cumulus-devseed-private

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'
     - name: InternalBucketName
       value: '{{buckets.internal}}'
     - name: PrivateBucketName
       value: '{{buckets.private}}'
     - name: ProtectedBucketName
       value: '{{buckets.protected}}'
     - name: PublicBucketName
       value: '{{buckets.public}}'
