default:
  prefix: sez
  stackName: sez-iam
  authorizor: false
  capabilities:
    - CAPABILITY_NAMED_IAM

  system_bucket: cumulus-developmentseed-internal

  buckets:
    internal:
      name: cumulus-developmentseed-internal
      type: internal
    private:
      name: cumulus-developmentseed-private
      type: private
    protected:
      name: cumulus-developmentseed-protected
      type: protected
    shared:
      name: cumulus-data-shared
      type: shared

  params:
     - name: ResourcePrefix
       value: '{{prefix}}'
